export interface ParkDetails {
  horario: string
  inclui: string[]
  naInclui: string[]
  alimentacao: string
  oQueTrazer: string[]
  estacionamento: string
  meiaEntrada: string[]
  gratuidade: string
  observacoes?: string
}

export const PARK_DETAILS: Record<string, ParkDetails> = {
  "hot-park": {
    horario: "09h00 às 17h00 (abertura pode variar na alta temporada)",
    inclui: ["Acesso a todas as atrações", "Toboáguas radicais", "Piscinas termais", "Rio lento", "Área infantil"],
    naInclui: ["Alimentação", "Estacionamento", "Fotos e filmagens profissionais"],
    alimentacao: "Não é permitido trazer alimentos ou bebidas de fora. Restaurantes, lanchonetes e bares disponíveis no parque.",
    oQueTrazer: ["Roupa de banho", "Toalha", "Protetor solar (obrigatório)", "Chinelo de borracha", "Óculos de sol", "Documento de identificação"],
    estacionamento: "Pago — R$ 25,00/dia",
    meiaEntrada: ["Idosos (60+) — obrigatório por lei", "Estudantes com carteirinha nacional", "Crianças 5–11 anos", "Autistas — gratuidade (com laudo)"],
    gratuidade: "Crianças até 4 anos entram gratuitamente",
    observacoes: "Hóspedes do Rio Quente Resorts têm acesso gratuito. Desconto especial para grupos a partir de 15 pessoas.",
  },
  "hot-park-crianca": {
    horario: "09h00 às 17h00",
    inclui: ["Toboáguas kids", "Piscina infantil", "Rio lento", "Área baby", "Almoço incluso"],
    naInclui: ["Estacionamento"],
    alimentacao: "Almoço incluso. Lanchonetes disponíveis no parque.",
    oQueTrazer: ["Roupa de banho", "Toalha", "Protetor solar", "Chinelo de borracha", "Documento de identificação da criança"],
    estacionamento: "Pago — R$ 25,00/dia",
    meiaEntrada: ["Crianças 5–11 anos — meia-entrada", "Autistas — gratuidade (com laudo)"],
    gratuidade: "Crianças até 4 anos entram gratuitamente",
  },
  "diroma-acqua-park": {
    horario: "09h00 às 17h00",
    inclui: ["Toboáguas variados", "Piscina de ondas", "Área kids", "Bar molhado", "Espreguiçadeiras"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Não é permitido trazer alimentos ou bebidas de fora. Restaurantes e bar molhado disponíveis.",
    oQueTrazer: ["Roupa de banho", "Toalha", "Protetor solar", "Chinelo de borracha", "Óculos de sol"],
    estacionamento: "Pago — área próxima ao parque",
    meiaEntrada: ["Idosos (60+)", "Estudantes com carteirinha", "Crianças 7–11 anos"],
    gratuidade: "Crianças até 5 anos entram gratuitamente",
    observacoes: "Área infantil temática com navio pirata. Vulcão com escorregadores.",
  },
  "lagoa-termas": {
    horario: "09h00 às 17h00",
    inclui: ["Águas termais naturais", "Trilhas ecológicas", "Área de descanso", "Lanchonete", "Estacionamento"],
    naInclui: ["Refeições completas"],
    alimentacao: "Lanchonete no local. Refeições não inclusas no ingresso.",
    oQueTrazer: ["Roupa de banho", "Toalha", "Protetor solar", "Chinelo", "Repelente"],
    estacionamento: "Gratuito — incluso no ingresso",
    meiaEntrada: ["Idosos (60+)", "Estudantes com carteirinha"],
    gratuidade: "Crianças até 10 anos entram gratuitamente",
    observacoes: "Parque mais completo de Caldas Novas. Estrutura ampla e moderna.",
  },
  "passaporte-kawana": {
    horario: "09h00 às 17h00 (todos os dias do passaporte)",
    inclui: ["3 dias de acesso", "Piscinas termais", "Toboáguas familiares", "Estacionamento grátis", "Área kids"],
    naInclui: ["Alimentação"],
    alimentacao: "Não inclui alimentação. Restaurantes e lanchonetes disponíveis no parque.",
    oQueTrazer: ["Roupa de banho", "Toalha", "Protetor solar", "Chinelo de borracha"],
    estacionamento: "Gratuito — incluso no passaporte",
    meiaEntrada: ["Idosos (60+)", "Estudantes com carteirinha", "Crianças 7–11 anos"],
    gratuidade: "Crianças até 6 anos entram gratuitamente",
    observacoes: "Parque mais radical do Centro-Oeste. Ideal para adolescentes e adultos.",
  },
  "transp-goiania": {
    horario: "Saída: 07h00 | Retorno: 18h00 (horários fixos)",
    inclui: ["Ônibus executivo com ar-condicionado", "Wi-Fi a bordo", "Seguro viagem"],
    naInclui: ["Alimentação durante o translado"],
    alimentacao: "Parada técnica programada com lanchonete.",
    oQueTrazer: ["Documento de identificação", "Comprovante de reserva", "Roupa confortável"],
    estacionamento: "Ponto de embarque com estacionamento gratuito",
    meiaEntrada: ["Idosos (60+)", "PCD — assento preferencial"],
    gratuidade: "Crianças de colo sem assento próprio",
    observacoes: "Duração aproximada: 3 horas. Saída pontual — apresente-se 15 minutos antes.",
  },
  "transp-brasilia": {
    horario: "Saída: 06h30 | Retorno: 18h30 (horários fixos)",
    inclui: ["Ônibus moderno", "Poltronas reclináveis", "Wi-Fi a bordo", "Lanche incluso", "Seguro viagem"],
    naInclui: [],
    alimentacao: "Lanche incluso durante o trajeto.",
    oQueTrazer: ["Documento de identificação", "Comprovante de reserva", "Roupa confortável"],
    estacionamento: "Ponto de embarque central — acesso fácil",
    meiaEntrada: ["Idosos (60+)", "PCD — assento preferencial"],
    gratuidade: "Crianças de colo sem assento próprio",
    observacoes: "Duração aproximada: 4 horas. Parada no meio do caminho.",
  },
  "water-park": {
    horario: "09h00 às 17h00",
    inclui: ["Hot Park completo", "diRoma Acqua Park", "Entrada prioritária", "Guia-mapa incluso"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Não inclui alimentação. Restaurantes disponíveis nos dois parques.",
    oQueTrazer: ["Roupa de banho extra", "Toalha", "Protetor solar", "Chinelo de borracha"],
    estacionamento: "Pago em cada parque",
    meiaEntrada: ["Idosos (60+)", "Estudantes com carteirinha", "Crianças 5–11 anos"],
    gratuidade: "Crianças até 4 anos (Hot Park) e até 5 anos (diRoma)",
    observacoes: "Combo mais pedido! Acesso a dois parques no mesmo dia.",
  },
  "kawana-park": {
    horario: "09h00 às 17h00",
    inclui: ["2 ingressos adulto", "1 ingresso criança", "Hot Park incluído", "Área infantil VIP", "Almoço incluso", "Pulseira ID kids"],
    naInclui: ["Estacionamento"],
    alimentacao: "Almoço incluso para toda a família. Bar disponível.",
    oQueTrazer: ["Roupa de banho (toda a família)", "Toalhas", "Protetor solar", "Chinelos"],
    estacionamento: "Pago — R$ 25,00/dia",
    meiaEntrada: ["Crianças 5–11 anos já incluso no combo"],
    gratuidade: "Crianças até 4 anos entram gratuitamente",
    observacoes: "Pulseira de identificação para crianças inclusa. Área infantil VIP com prioridade.",
  },
  "combo-3-parques": {
    horario: "09h00 às 17h00 (por 3 dias consecutivos)",
    inclui: ["Hot Park", "diRoma Acqua Park", "Lagoa Termas", "3 dias de acesso", "Café da manhã incluso", "Transfer entre parques"],
    naInclui: ["Almoço e jantar", "Hospedagem"],
    alimentacao: "Café da manhã incluso nos 3 dias. Demais refeições não inclusas.",
    oQueTrazer: ["Roupa de banho extra", "Toalhas", "Protetor solar", "Chinelos", "Mochila pequena"],
    estacionamento: "Transfer entre parques incluso — estacionamento não necessário",
    meiaEntrada: ["Idosos (60+)", "Estudantes com carteirinha", "Crianças 5–11 anos"],
    gratuidade: "Crianças até 4-5 anos (varia por parque)",
    observacoes: "A experiência definitiva em 3 dias. Transfer entre parques incluso no combo.",
  },
  "ingresso-vip": {
    horario: "09h00 às 18h00 (1 hora extra — entrada VIP)",
    inclui: ["Fast pass — sem filas", "Área VIP exclusiva", "Serviço de mordomo", "Bebidas inclusas", "Fotos profissionais"],
    naInclui: ["Alimentação completa"],
    alimentacao: "Bebidas inclusas. Cardápio completo disponível no restaurante VIP.",
    oQueTrazer: ["Documento de identificação", "Roupa de banho", "Protetor solar"],
    estacionamento: "Pago — valet disponível para VIPs",
    meiaEntrada: ["Não aplicável para ingressos VIP"],
    gratuidade: "Não aplicável",
    observacoes: "Experiência premium com atendimento exclusivo. Capacidade limitada.",
  },
  "ingresso-noturno": {
    horario: "17h00 às 23h00 (somente noturno)",
    inclui: ["Entrada a partir das 17h", "Show ao vivo", "Coquetel de boas-vindas", "Iluminação temática"],
    naInclui: ["Alimentação completa"],
    alimentacao: "Coquetel de boas-vindas incluso. Bar disponível durante o evento.",
    oQueTrazer: ["Documento de identificação", "Roupa adequada (pode esfriar à noite)", "Roupa de banho"],
    estacionamento: "Pago — R$ 15,00/noite",
    meiaEntrada: ["Não aplicável para eventos noturnos"],
    gratuidade: "Somente para maiores de 18 anos",
    observacoes: "Evento especial com música ao vivo. Verificar programação da data escolhida.",
  },
  "ingresso-open-hotel": {
    horario: "Check-in: 14h00 | Parques: 09h00 às 17h00",
    inclui: ["Open ingressos (3 parques)", "1 noite em hotel 4★", "Café da manhã incluso", "Transfer aeroporto"],
    naInclui: ["Demais refeições", "Despesas pessoais"],
    alimentacao: "Café da manhã incluso no hotel. Restaurantes disponíveis nos parques.",
    oQueTrazer: ["Documentos", "Roupa de banho", "Roupas para 2 dias", "Protetor solar"],
    estacionamento: "Incluso no hotel",
    meiaEntrada: ["Idosos (60+)", "Estudantes", "PCD"],
    gratuidade: "Crianças até 5 anos (parques) e até 6 anos (hotel, com adulto pagante)",
    observacoes: "A viagem completa! Combine parques e hospedagem com praticidade total.",
  },
  "cabana-standard": {
    horario: "09h00 às 17h00",
    inclui: ["4 espreguiçadeiras", "Mesa e cadeiras", "Guarda-sol premium", "Frigobar", "Serviço de garçom", "Toalhas"],
    naInclui: ["Ingressos do parque (compra separada)", "Consumo do frigobar"],
    alimentacao: "Serviço de garçom disponível. Pedidos à la carte com cardápio especial de cabana.",
    oQueTrazer: ["Protetor solar", "Roupas confortáveis", "Itens pessoais"],
    estacionamento: "Pago — R$ 25,00/dia",
    meiaEntrada: ["N/A — cabana não inclui ingresso"],
    gratuidade: "N/A — cabana não inclui ingresso",
    observacoes: "Ingresso do parque deve ser adquirido separadamente. Cabana garante área exclusiva.",
  },
  "cabana-premium": {
    horario: "09h00 às 17h00",
    inclui: ["6 espreguiçadeiras", "Área gourmet", "Frigobar premium abastecido", "TV com streaming", "Serviço exclusivo"],
    naInclui: ["Ingressos do parque", "Consumo adicional de bebidas premium"],
    alimentacao: "Frigobar abastecido incluso. Serviço de garçom exclusivo da cabana.",
    oQueTrazer: ["Protetor solar", "Roupas de banho", "Itens pessoais"],
    estacionamento: "Pago — estacionamento VIP disponível",
    meiaEntrada: ["N/A — cabana não inclui ingresso"],
    gratuidade: "N/A — cabana não inclui ingresso",
    observacoes: "Ideal para aniversários e grupos especiais. Reserve com antecedência.",
  },
  "cabana-exclusive": {
    horario: "09h00 às 18h00 (1 hora extra exclusiva)",
    inclui: ["10 espreguiçadeiras", "Piscina privativa", "Chef exclusivo", "Open bar", "Acesso VIP total"],
    naInclui: ["Ingressos do parque"],
    alimentacao: "Chef exclusivo e open bar incluso na cabana.",
    oQueTrazer: ["Protetor solar", "Roupas de banho", "Itens pessoais"],
    estacionamento: "Valet incluso para Cabana Exclusive",
    meiaEntrada: ["N/A — cabana não inclui ingresso"],
    gratuidade: "N/A — cabana não inclui ingresso",
    observacoes: "A experiência máxima. Capacidade para até 10 pessoas com serviço 5 estrelas.",
  },
  "morador-hot-park": {
    horario: "09h00 às 17h00",
    inclui: ["Acesso a todas as atrações", "Toboáguas radicais", "Piscinas termais", "Rio lento", "Área infantil"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Não inclui alimentação. Restaurantes disponíveis no parque.",
    oQueTrazer: ["RG com endereço de Caldas Novas ou Rio Quente", "Comprovante de residência", "Roupa de banho", "Protetor solar"],
    estacionamento: "Pago — R$ 25,00/dia",
    meiaEntrada: ["Idosos moradores (60+)", "Estudantes moradores"],
    gratuidade: "Crianças até 4 anos entram gratuitamente",
    observacoes: "Desconto exclusivo para moradores de Caldas Novas e Rio Quente. Apresentar RG + comprovante de residência na bilheteria.",
  },
  "morador-diroma": {
    horario: "09h00 às 17h00",
    inclui: ["Toboáguas variados", "Piscina de ondas", "Área kids", "Bar molhado"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Não inclui alimentação. Bar e lanchonete disponíveis.",
    oQueTrazer: ["RG com endereço de Caldas Novas", "Comprovante de residência", "Roupa de banho", "Protetor solar"],
    estacionamento: "Pago — área próxima ao parque",
    meiaEntrada: ["Idosos moradores (60+)", "Estudantes moradores"],
    gratuidade: "Crianças até 5 anos entram gratuitamente",
    observacoes: "Desconto exclusivo para moradores de Caldas Novas. Apresentar documentos na bilheteria.",
  },
  "morador-lagoa": {
    horario: "09h00 às 17h00",
    inclui: ["Águas termais naturais", "Área de descanso", "Lanchonete", "Estacionamento"],
    naInclui: ["Refeições completas"],
    alimentacao: "Lanchonete disponível. Refeições não inclusas.",
    oQueTrazer: ["RG com endereço de Caldas Novas", "Comprovante de residência", "Roupa de banho", "Protetor solar"],
    estacionamento: "Gratuito — incluso no ingresso",
    meiaEntrada: ["Idosos moradores (60+)"],
    gratuidade: "Crianças até 10 anos entram gratuitamente",
    observacoes: "Benefício para moradores. Apresentar RG + comprovante de residência.",
  },
  "morador-kawana": {
    horario: "09h00 às 17h00",
    inclui: ["Piscinas termais", "Toboáguas gigantes", "Piscina de ondas", "Rio lento"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Não inclui alimentação. Lanchonetes disponíveis.",
    oQueTrazer: ["RG com endereço de Caldas Novas", "Comprovante de residência", "Roupa de banho", "Protetor solar"],
    estacionamento: "Pago",
    meiaEntrada: ["Idosos moradores (60+)", "Estudantes moradores"],
    gratuidade: "Crianças até 6 anos entram gratuitamente",
    observacoes: "Kawana Park — o mais radical do Centro-Oeste. Desconto morador aplicado na bilheteria.",
  },
  "meia-idoso": {
    horario: "09h00 às 17h00 (varia por parque)",
    inclui: ["Acesso ao parque escolhido (meia-entrada por lei federal)"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Varia por parque. Consulte cada parque.",
    oQueTrazer: ["RG ou CNH (documento oficial com foto e data de nascimento)", "Roupa de banho", "Protetor solar"],
    estacionamento: "Varia por parque",
    meiaEntrada: ["Idosos com 60 anos ou mais — obrigatório por lei federal"],
    gratuidade: "Varia por parque",
    observacoes: "Direito garantido por lei federal. Apresentar documento com data de nascimento na bilheteria. Válido para: Hot Park, diRoma, Lagoa Termas, Kawana, Water Park, Clube Privé e outros.",
  },
  "meia-estudante": {
    horario: "09h00 às 17h00 (varia por parque)",
    inclui: ["Acesso ao parque escolhido (meia-entrada por lei)"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Varia por parque.",
    oQueTrazer: ["Carteirinha estudantil nacional (CIE/UNE/ANIPES)", "Documento de identificação", "Roupa de banho", "Protetor solar"],
    estacionamento: "Varia por parque",
    meiaEntrada: ["Estudantes com carteirinha nacional válida — Lei da Meia-Entrada"],
    gratuidade: "N/A",
    observacoes: "Válido em todos os parques (Water Park, Hot Park, diRoma, Kawana, etc.). Apresentar carteirinha válida + documento com foto. Carteirinha física ou digital.",
  },
  "meia-pcd": {
    horario: "09h00 às 17h00 (varia por parque)",
    inclui: ["Acesso especial ou gratuidade (varia por parque)"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Varia por parque.",
    oQueTrazer: ["Laudo médico atualizado (CID)", "Documento de identificação", "Roupa de banho"],
    estacionamento: "Vaga preferencial disponível",
    meiaEntrada: ["Pessoas com Deficiência (PCD) — ingresso especial ou gratuidade com laudo"],
    gratuidade: "Alguns parques concedem gratuidade total para PCD com laudo",
    observacoes: "Apresentar laudo médico com CID na bilheteria. Hot Park oferece Day Use PCD especial. Acessibilidade disponível nos principais parques.",
  },
  "meia-professor": {
    horario: "09h00 às 17h00",
    inclui: ["Acesso ao parque (Water Park ou Clube Privé)"],
    naInclui: ["Alimentação", "Estacionamento"],
    alimentacao: "Não inclui alimentação.",
    oQueTrazer: ["Último contracheque comprovando profissão", "Documento de identificação com foto", "Roupa de banho", "Protetor solar"],
    estacionamento: "Pago",
    meiaEntrada: ["Professores com comprovante de atividade — Water Park e Clube Privé"],
    gratuidade: "N/A",
    observacoes: "Desconto para professores disponível apenas no Water Park e Clube Privé. Não válido para Hot Park nem Náutico Praia Clube. Apresentar último contracheque + documento com foto.",
  },
}
