import { eq, sql } from "drizzle-orm";
import { NodePgDatabase } from "drizzle-orm/node-postgres";
import { websitePages, websiteSettings, websiteMedia } from "../../shared/schema.js";
import { LANDING_PAGES } from "../../shared/website-types.js";

/* ─────────────────────────────────────────────────────────────────────────────
   RSV360 — Website CMS seed (idempotente)
   Usa onConflictDoUpdate para garantir que páginas existentes tenham
   status="published" e access="public" mesmo se criadas antes da coluna existir.
   ───────────────────────────────────────────────────────────────────────────── */

const LANDING_PAGES_SEED = [
  ...LANDING_PAGES.map((lp) => ({
    slug: lp.slug,
    title: lp.label,
    section: lp.section,
    status: "published" as const,
    access: "public" as const,
    metaTitle: `${lp.label} — RSV360`,
    metaDescription: `RSV360 — ${lp.label}: Caldas Novas e Rio Quente, a melhor plataforma de turismo termal.`,
    content: { sections: [], theme: {}, seo: {} },
    publishedAt: new Date("2026-01-01"),
  })),
  {
    slug: "sobre",
    title: "Sobre Nós",
    section: "main" as const,
    status: "published" as const,
    access: "public" as const,
    metaTitle: "Sobre a RSV360 — Quem somos",
    metaDescription: "A RSV360 é especialista em turismo termal em Caldas Novas e Rio Quente, Goiás.",
    content: { sections: [], theme: {}, seo: {} },
    publishedAt: new Date("2026-01-01"),
  },
  {
    slug: "politica-de-privacidade",
    title: "Política de Privacidade",
    section: "main" as const,
    status: "published" as const,
    access: "public" as const,
    metaTitle: "Política de Privacidade — RSV360",
    metaDescription: "Como a RSV360 coleta, usa e protege seus dados pessoais.",
    content: { sections: [], theme: {}, seo: {} },
    publishedAt: new Date("2026-01-01"),
  },
];

const DEMO_PAGES = LANDING_PAGES_SEED;

const DEFAULT_SETTINGS = {
  id: 1,
  siteName: "RSV360",
  primaryColor: "#1a56db",
  contactEmail: "contato@reservei.com.br",
  contactPhone: "+55 64 99999-0000",
  socialLinks: {
    instagram: "https://instagram.com/reservei",
    whatsapp: "https://wa.me/5564999990000",
  },
};

type MediaSeedEntry = {
  filename: string;
  originalName: string;
  mimetype: string;
  sizeBytes: number;
  url: string;
  altText: string;
  type: "image" | "video" | "document";
  placement: "hero" | "card" | "banner" | "gallery" | "avatar" | "icon" | "background" | "misc";
  status: "active" | "archived" | "orphan";
  pageSlug?: string;
};

const DEMO_MEDIA: MediaSeedEntry[] = [
  /* ── Global / Site identity ─────────────────────────────────────────── */
  {
    filename: "logo-rsv360.png",
    originalName: "logo-rsv360.png",
    mimetype: "image/png",
    sizeBytes: 0,
    url: "/uploads/website/logo-rsv360.png",
    altText: "Logo RSV360",
    type: "image",
    placement: "avatar",
    status: "active",
  },
  {
    filename: "banner-hot-park.jpg",
    originalName: "banner-hot-park.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "/uploads/website/banner-hot-park.jpg",
    altText: "Hot Park — Rio Quente Resorts",
    type: "image",
    placement: "banner",
    status: "active",
  },

  /* ── Home / Landing ─────────────────────────────────────────────────── */
  {
    filename: "hero-home-caldas-novas.jpg",
    originalName: "hero-home-caldas-novas.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=60",
    altText: "Vista aérea das águas termais de Caldas Novas",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "home",
  },
  {
    filename: "home-hot-park-card.jpg",
    originalName: "home-hot-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-Jm2Xy9K8RfqL3vN5wT1pA6sD4hB7eC.jpg",
    altText: "Hot Park Rio Quente — card inicial",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "home",
  },
  {
    filename: "home-diroma-card.jpg",
    originalName: "home-diroma-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-Kp4Mn7Hs8Qf2Lw6Rv3Jx5Bt1Yd9Gc.jpg",
    altText: "diRoma Acqua Park — card inicial",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "home",
  },
  {
    filename: "home-termas-paradise-card.jpg",
    originalName: "home-termas-paradise-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/termas-paradise-Np6Qr8Ts2Uf4Xv7Zy1Bw3Dc5Eg9Hj.jpg",
    altText: "Termas Paradise — card inicial",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "home",
  },
  {
    filename: "home-water-park-card.jpg",
    originalName: "home-water-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/water-park-Lq8Rs2Ut4Wv6Xy9Ab1Cd3Ef5Gh7Ij.jpg",
    altText: "Water Park Caldas Novas — card inicial",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "home",
  },

  /* ── Hotéis ─────────────────────────────────────────────────────────── */
  {
    filename: "hoteis-hero-bg.jpg",
    originalName: "hoteis-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1600&q=80",
    altText: "Hero background — Hotéis Caldas Novas",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-hot-park-1.jpg",
    originalName: "hotel-hot-park-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-rio-quente-resort-1-vb7vdyxEIIlbS2bWqxwBp7IaRi7x7F.jpeg",
    altText: "Hot Park Rio Quente Resort — imagem 1",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-hot-park-2.jpg",
    originalName: "hotel-hot-park-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-rio-quente-resort-2-jKlP9nMxR8qZwYhVtCx4yS2fNpQr3D.jpeg",
    altText: "Hot Park Rio Quente Resort — imagem 2",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-hot-park-3.jpg",
    originalName: "hotel-hot-park-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-rio-quente-resort-3-aB3cDeFgH5iJkLmN7oPqRsTuV9wXyZ.jpeg",
    altText: "Hot Park Rio Quente Resort — imagem 3",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-golden-dolphin-1.jpg",
    originalName: "hotel-golden-dolphin-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/golden-dolphin-1-mN7oPqRsTuV9wXyZ1aB2cDeFgH3iJk.jpeg",
    altText: "Golden Dolphin Grand Hotel — imagem 1",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-golden-dolphin-2.jpg",
    originalName: "hotel-golden-dolphin-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/golden-dolphin-2-kLmN7oPqRsTuV9wXyZ1aB2cDeFgH3i.jpeg",
    altText: "Golden Dolphin Grand Hotel — imagem 2",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-diroma-1.jpg",
    originalName: "hotel-diroma-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-1-pQrStUvW9xYz1aB2cDeFgH3iJkLmN7o.jpeg",
    altText: "diRoma Acqua Park Hotel — imagem 1",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-diroma-2.jpg",
    originalName: "hotel-diroma-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-2-rStUvW9xYz1aB2cDeFgH3iJkLmN7oPq.jpeg",
    altText: "diRoma Acqua Park Hotel — imagem 2",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-lacqua-1.jpg",
    originalName: "hotel-lacqua-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lacqua-1-tUvW9xYz1aB2cDeFgH3iJkLmN7oPqRs.jpeg",
    altText: "Lacqua di Roma Resort — imagem 1",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "hotel-prive-1.jpg",
    originalName: "hotel-prive-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/prive-1-vW9xYz1aB2cDeFgH3iJkLmN7oPqRsTu.jpeg",
    altText: "Privé Caldas Novas — imagem 1",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "hoteis",
  },

  /* ── Atrações ────────────────────────────────────────────────────────── */
  {
    filename: "atracoes-hero-bg.jpg",
    originalName: "atracoes-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/O-que-fazer-em-Caldas-Novas-alem-dos-parques-.jpg-hggVCc4sV9K9nxiHfEglNOYL1NO3Mr.jpeg",
    altText: "O que fazer em Caldas Novas — hero atrações",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "atracao-jardim-japones.jpg",
    originalName: "atracao-jardim-japones.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images.jfif-qEh8dMMyYkqDeGxaBMbhqplQXVSpEU.jpeg",
    altText: "Jardim Japonês — Caldas Novas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "atracao-lago-corumba.jpg",
    originalName: "atracao-lago-corumba.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/97cea591709031183bf3c175de4d26c4.jpg-hDxD6ZNoJL0WRJF9sZC84493RoYy4A.jpeg",
    altText: "Lago Corumbá — Caldas Novas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "atracao-monumento-aguas.jpg",
    originalName: "atracao-monumento-aguas.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/monumento-as-aguas.jpg-23Ox7hDb2v9O7MvysJbMC402VHtIJ2.jpeg",
    altText: "Monumento das Águas — Caldas Novas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "atracao-feira-luar.jpg",
    originalName: "atracao-feira-luar.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/unnamed.jpg-kMID5PSp6hxQkx36Qp540D7NUs1N9Y.jpeg",
    altText: "Feira do Luar — Caldas Novas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "atracao-parque-estadual.jpg",
    originalName: "atracao-parque-estadual.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Entrada-do-PESCAN-Parque-da-Serra-de-Caldas.jpg-1dCOLwSaVTKLgUQ35R0f6eVwQ20xhX.jpeg",
    altText: "Parque Estadual da Serra de Caldas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "atracao-centro-historico.jpg",
    originalName: "atracao-centro-historico.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/O-que-fazer-em-Caldas-Novas-alem-dos-parques-.jpg-hggVCc4sV9K9nxiHfEglNOYL1NO3Mr.jpeg",
    altText: "Centro Histórico de Caldas Novas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "atracoes",
  },

  /* ── Ingressos ───────────────────────────────────────────────────────── */
  {
    filename: "ingressos-lagoa-termas.jpeg",
    originalName: "ingressos-lagoa-termas.jpeg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "/images/lagoa-termas-parque.jpeg",
    altText: "Lagoa Termas Parque — ingresso",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "ingressos-hot-park.jpeg",
    originalName: "ingressos-hot-park.jpeg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "/images/hot-park.jpeg",
    altText: "Hot Park — ingresso",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "ingressos-diroma-acqua.jpeg",
    originalName: "ingressos-diroma-acqua.jpeg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "/images/diroma-acqua-park.jpeg",
    altText: "diRoma Acqua Park — ingresso",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "ingressos-kawana-park.jpeg",
    originalName: "ingressos-kawana-park.jpeg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "/images/kawana-park.jpeg",
    altText: "Kawana Park — ingresso",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "ingressos-water-park.jpeg",
    originalName: "ingressos-water-park.jpeg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "/images/water-park.jpeg",
    altText: "Water Park — ingresso combo",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ingressos",
  },

  /* ── Excursões ───────────────────────────────────────────────────────── */
  {
    filename: "excursoes-hero-bg.jpg",
    originalName: "excursoes-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=1600&q=80",
    altText: "Hero — Excursões e pacotes de viagem",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "excursoes",
  },
  {
    filename: "excursoes-card-praia.jpg",
    originalName: "excursoes-card-praia.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    altText: "Excursão — card praia e lazer",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "excursoes",
  },
  {
    filename: "excursoes-card-hotel.jpg",
    originalName: "excursoes-card-hotel.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&q=80",
    altText: "Excursão — card hotel",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "excursoes",
  },

  /* ── Catálogo de Excursões ───────────────────────────────────────────── */
  {
    filename: "catalogo-excursoes-hero.jpg",
    originalName: "catalogo-excursoes-hero.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&q=80",
    altText: "Catálogo de excursões — hero",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "catalogo",
  },
  {
    filename: "catalogo-excursoes-card-1.jpg",
    originalName: "catalogo-excursoes-card-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    altText: "Catálogo de excursões — card 1",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "catalogo",
  },
  {
    filename: "catalogo-excursoes-card-2.jpg",
    originalName: "catalogo-excursoes-card-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&q=80",
    altText: "Catálogo de excursões — card 2",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "catalogo",
  },

  /* ── Leilões ─────────────────────────────────────────────────────────── */
  {
    filename: "leiloes-hero-bg.jpg",
    originalName: "leiloes-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1600&q=80",
    altText: "Leilões — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "leiloes",
  },
  {
    filename: "leiloes-hot-park-card.jpg",
    originalName: "leiloes-hot-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-Jm2Xy9K8RfqL3vN5wT1pA6sD4hB7eC.jpg",
    altText: "Leilões — Hot Park card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "leiloes",
  },
  {
    filename: "leiloes-diroma-card.jpg",
    originalName: "leiloes-diroma-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-Kp4Mn7Hs8Qf2Lw6Rv3Jx5Bt1Yd9Gc.jpg",
    altText: "Leilões — diRoma card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "leiloes",
  },
  {
    filename: "leiloes-termas-paradise-card.jpg",
    originalName: "leiloes-termas-paradise-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/termas-paradise-Np6Qr8Ts2Uf4Xv7Zy1Bw3Dc5Eg9Hj.jpg",
    altText: "Leilões — Termas Paradise card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "leiloes",
  },

  /* ── Promoções ───────────────────────────────────────────────────────── */
  {
    filename: "promocoes-hero-bg.jpg",
    originalName: "promocoes-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=80",
    altText: "Promoções — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "promocoes",
  },
  {
    filename: "promocoes-hot-park-card.jpg",
    originalName: "promocoes-hot-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-Jm2Xy9K8RfqL3vN5wT1pA6sD4hB7eC.jpg",
    altText: "Promoções — Hot Park card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "promocoes",
  },
  {
    filename: "promocoes-diroma-card.jpg",
    originalName: "promocoes-diroma-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-Kp4Mn7Hs8Qf2Lw6Rv3Jx5Bt1Yd9Gc.jpg",
    altText: "Promoções — diRoma card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "promocoes",
  },
  {
    filename: "promocoes-water-park-card.jpg",
    originalName: "promocoes-water-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/water-park-Lq8Rs2Ut4Wv6Xy9Ab1Cd3Ef5Gh7Ij.jpg",
    altText: "Promoções — Water Park card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "promocoes",
  },

  /* ── Ofertas (Flash Deals) ───────────────────────────────────────────── */
  {
    filename: "ofertas-hero-bg.jpg",
    originalName: "ofertas-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1600&q=80",
    altText: "Ofertas — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "ofertas",
  },
  {
    filename: "ofertas-hot-park-card.jpg",
    originalName: "ofertas-hot-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-Jm2Xy9K8RfqL3vN5wT1pA6sD4hB7eC.jpg",
    altText: "Ofertas — Hot Park card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ofertas",
  },
  {
    filename: "ofertas-diroma-card.jpg",
    originalName: "ofertas-diroma-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-Kp4Mn7Hs8Qf2Lw6Rv3Jx5Bt1Yd9Gc.jpg",
    altText: "Ofertas — diRoma card",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "ofertas",
  },

  /* ── Galerias por página (placement="gallery") — 3-4 imagens + 1 vídeo YouTube ── */

  /* ·· Hotéis ·· */
  {
    filename: "gallery-hoteis-1.jpg",
    originalName: "gallery-hoteis-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80",
    altText: "Hotéis — resort com piscina termal",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "gallery-hoteis-2.jpg",
    originalName: "gallery-hoteis-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900&q=80",
    altText: "Hotéis — piscina panorâmica do resort",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "gallery-hoteis-3.jpg",
    originalName: "gallery-hoteis-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=900&q=80",
    altText: "Hotéis — quarto luxuoso com vista",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },
  {
    filename: "gallery-hoteis-video.mp4",
    originalName: "https://www.youtube.com/watch?v=rVxF7Kx4w3M",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=rVxF7Kx4w3M",
    altText: "Hotéis de Caldas Novas — Resort Tour",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "hoteis",
  },

  /* ·· Atrações ·· */
  {
    filename: "gallery-atracoes-1.jpg",
    originalName: "gallery-atracoes-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80",
    altText: "Atrações — praia termal ao entardecer",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "gallery-atracoes-2.jpg",
    originalName: "gallery-atracoes-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=900&q=80",
    altText: "Atrações — paisagem natural de Caldas Novas",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "gallery-atracoes-3.jpg",
    originalName: "gallery-atracoes-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=900&q=80",
    altText: "Atrações — vista panorâmica da região",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "gallery-atracoes-4.jpg",
    originalName: "gallery-atracoes-4.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=900&q=80",
    altText: "Atrações — lago e natureza",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "atracoes",
  },
  {
    filename: "gallery-atracoes-video.mp4",
    originalName: "https://www.youtube.com/watch?v=ZCR3CkG2r74",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=ZCR3CkG2r74",
    altText: "Atrações de Caldas Novas — o que fazer na cidade",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "atracoes",
  },

  /* ·· Ingressos ·· */
  {
    filename: "gallery-ingressos-1.jpg",
    originalName: "gallery-ingressos-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&q=80",
    altText: "Ingressos — parque aquático e diversão",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "gallery-ingressos-2.jpg",
    originalName: "gallery-ingressos-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&q=80",
    altText: "Ingressos — piscinas termais",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "gallery-ingressos-3.jpg",
    originalName: "gallery-ingressos-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=900&q=80",
    altText: "Ingressos — toboágua e atrações aquáticas",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "ingressos",
  },
  {
    filename: "gallery-ingressos-video.mp4",
    originalName: "https://www.youtube.com/watch?v=yLcf_VJ3VfY",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=yLcf_VJ3VfY",
    altText: "Ingressos Hot Park — tour completo pelo parque",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "ingressos",
  },

  /* ·· Excursões ·· */
  {
    filename: "gallery-excursoes-1.jpg",
    originalName: "gallery-excursoes-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=900&q=80",
    altText: "Excursões — viagem em grupo",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "excursoes",
  },
  {
    filename: "gallery-excursoes-2.jpg",
    originalName: "gallery-excursoes-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=900&q=80",
    altText: "Excursões — ônibus de viagem confortável",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "excursoes",
  },
  {
    filename: "gallery-excursoes-3.jpg",
    originalName: "gallery-excursoes-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80",
    altText: "Excursões — paisagens incríveis pelo caminho",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "excursoes",
  },
  {
    filename: "gallery-excursoes-video.mp4",
    originalName: "https://www.youtube.com/watch?v=GNM84rOhPqI",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=GNM84rOhPqI",
    altText: "Excursões para Caldas Novas — guia completo",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "excursoes",
  },

  /* ·· Promoções ·· */
  {
    filename: "gallery-promocoes-1.jpg",
    originalName: "gallery-promocoes-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=900&q=80",
    altText: "Promoções — desconto em hotéis e parques",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "promocoes",
  },
  {
    filename: "gallery-promocoes-2.jpg",
    originalName: "gallery-promocoes-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&q=80",
    altText: "Promoções — pacotes especiais de férias",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "promocoes",
  },
  {
    filename: "gallery-promocoes-3.jpg",
    originalName: "gallery-promocoes-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900&q=80",
    altText: "Promoções — resort com piscina termal",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "promocoes",
  },
  {
    filename: "gallery-promocoes-video.mp4",
    originalName: "https://www.youtube.com/watch?v=C0Ak5cJD2yg",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=C0Ak5cJD2yg",
    altText: "Melhores hotéis de Caldas Novas em promoção",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "promocoes",
  },

  /* ·· Ofertas (Flash Deals) ·· */
  {
    filename: "gallery-ofertas-1.jpg",
    originalName: "gallery-ofertas-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=80",
    altText: "Flash Deals — ofertas relâmpago em resorts",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "ofertas",
  },
  {
    filename: "gallery-ofertas-2.jpg",
    originalName: "gallery-ofertas-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=900&q=80",
    altText: "Flash Deals — piscina de resort termal",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "ofertas",
  },
  {
    filename: "gallery-ofertas-3.jpg",
    originalName: "gallery-ofertas-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=900&q=80",
    altText: "Flash Deals — quarto de hotel com desconto",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "ofertas",
  },
  {
    filename: "gallery-ofertas-video.mp4",
    originalName: "https://www.youtube.com/watch?v=6DzdFhLGkiE",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=6DzdFhLGkiE",
    altText: "Flash Deals — melhor custo-benefício em Caldas Novas",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "ofertas",
  },

  /* ·· Leilões ·· */
  {
    filename: "gallery-leiloes-1.jpg",
    originalName: "gallery-leiloes-1.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=900&q=80",
    altText: "Leilões — apartamentos e pacotes em leilão",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "leiloes",
  },
  {
    filename: "gallery-leiloes-2.jpg",
    originalName: "gallery-leiloes-2.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=900&q=80",
    altText: "Leilões — hotel boutique disponível em leilão",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "leiloes",
  },
  {
    filename: "gallery-leiloes-3.jpg",
    originalName: "gallery-leiloes-3.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=900&q=80",
    altText: "Leilões — pacote de viagem em leilão relâmpago",
    type: "image",
    placement: "gallery",
    status: "active",
    pageSlug: "leiloes",
  },
  {
    filename: "gallery-leiloes-video.mp4",
    originalName: "https://www.youtube.com/watch?v=L3J3-pTmTpA",
    mimetype: "video/external",
    sizeBytes: 0,
    url: "https://www.youtube.com/watch?v=L3J3-pTmTpA",
    altText: "Como funciona o leilão de viagens na RSV360",
    type: "video",
    placement: "gallery",
    status: "active",
    pageSlug: "leiloes",
  },

  /* ── Caldas AI ───────────────────────────────────────────────────────── */
  {
    filename: "caldas-ai-hero-bg.jpg",
    originalName: "caldas-ai-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1600&q=80",
    altText: "Caldas AI — hero background IA",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "caldas-ai",
  },
  {
    filename: "caldas-ai-hot-park-recomendacao.jpg",
    originalName: "caldas-ai-hot-park-recomendacao.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-Jm2Xy9K8RfqL3vN5wT1pA6sD4hB7eC.jpg",
    altText: "Caldas AI — Hot Park recomendação",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "caldas-ai",
  },
  {
    filename: "caldas-ai-diroma-recomendacao.jpg",
    originalName: "caldas-ai-diroma-recomendacao.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-Kp4Mn7Hs8Qf2Lw6Rv3Jx5Bt1Yd9Gc.jpg",
    altText: "Caldas AI — diRoma recomendação",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "caldas-ai",
  },
  {
    filename: "caldas-ai-water-park-recomendacao.jpg",
    originalName: "caldas-ai-water-park-recomendacao.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/water-park-Lq8Rs2Ut4Wv6Xy9Ab1Cd3Ef5Gh7Ij.jpg",
    altText: "Caldas AI — Water Park recomendação",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "caldas-ai",
  },

  /* ── Viagens em Grupo ────────────────────────────────────────────────── */
  {
    filename: "grupos-hero-bg.jpg",
    originalName: "grupos-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1600&q=80",
    altText: "Viagens em Grupo — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "grupos",
  },
  {
    filename: "grupos-hot-park-card.jpg",
    originalName: "grupos-hot-park-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hot-park-Jm2Xy9K8RfqL3vN5wT1pA6sD4hB7eC.jpg",
    altText: "Viagens em Grupo — Hot Park",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "grupos",
  },
  {
    filename: "grupos-diroma-card.jpg",
    originalName: "grupos-diroma-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/diroma-Kp4Mn7Hs8Qf2Lw6Rv3Jx5Bt1Yd9Gc.jpg",
    altText: "Viagens em Grupo — diRoma",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "grupos",
  },
  {
    filename: "grupos-termas-paradise-card.jpg",
    originalName: "grupos-termas-paradise-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/termas-paradise-Np6Qr8Ts2Uf4Xv7Zy1Bw3Dc5Eg9Hj.jpg",
    altText: "Viagens em Grupo — Termas Paradise",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "grupos",
  },

  /* ── Quem Somos ──────────────────────────────────────────────────────── */
  {
    filename: "quem-somos-hero-bg.jpg",
    originalName: "quem-somos-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&q=80",
    altText: "Quem Somos — RSV360 team hero",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "quem-somos",
  },
  {
    filename: "quem-somos-team-card.jpg",
    originalName: "quem-somos-team-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&q=80",
    altText: "Quem Somos — equipe RSV360",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "quem-somos",
  },

  /* ── Perfil ──────────────────────────────────────────────────────────── */
  {
    filename: "perfil-hero-bg.jpg",
    originalName: "perfil-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=1600&q=80",
    altText: "Perfil do viajante — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "perfil",
  },
  {
    filename: "perfil-avatar-placeholder.jpg",
    originalName: "perfil-avatar-placeholder.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=200&q=80",
    altText: "Perfil — avatar placeholder",
    type: "image",
    placement: "avatar",
    status: "active",
    pageSlug: "perfil",
  },

  /* ── Mapas ───────────────────────────────────────────────────────────── */
  {
    filename: "mapas-hero-bg.jpg",
    originalName: "mapas-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1600&q=80",
    altText: "Mapa de Caldas Novas — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "mapas",
  },
  {
    filename: "mapas-caldas-novas-overview.jpg",
    originalName: "mapas-caldas-novas-overview.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80",
    altText: "Mapa turístico de Caldas Novas",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "mapas",
  },

  /* ── Contato ─────────────────────────────────────────────────────────── */
  {
    filename: "contato-hero-bg.jpg",
    originalName: "contato-hero-bg.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1423666639041-f56000c27a9a?w=1600&q=80",
    altText: "Contato RSV360 — hero background",
    type: "image",
    placement: "hero",
    status: "active",
    pageSlug: "contato",
  },
  {
    filename: "contato-whatsapp-card.jpg",
    originalName: "contato-whatsapp-card.jpg",
    mimetype: "image/jpeg",
    sizeBytes: 0,
    url: "https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=600&q=80",
    altText: "Contato via WhatsApp",
    type: "image",
    placement: "card",
    status: "active",
    pageSlug: "contato",
  },
];

export async function seedWebsite(db: NodePgDatabase): Promise<void> {
  let pagesUpserted = 0;

  for (const page of DEMO_PAGES) {
    await db
      .insert(websitePages)
      .values({
        title: page.title,
        slug: page.slug,
        section: page.section,
        status: page.status,
        access: page.access,
        metaTitle: page.metaTitle,
        metaDescription: page.metaDescription,
        content: page.content,
        publishedAt: page.publishedAt,
      })
      .onConflictDoUpdate({
        target: websitePages.slug,
        set: {
          status: "published",
          access: "public",
          updatedAt: sql`now()`,
        },
      });
    pagesUpserted++;
  }

  const existingSettings = await db
    .select({ id: websiteSettings.id })
    .from(websiteSettings)
    .where(eq(websiteSettings.id, 1))
    .limit(1);

  let settingsAction: "created" | "skipped";
  if (existingSettings.length === 0) {
    await db.insert(websiteSettings).values(DEFAULT_SETTINGS);
    settingsAction = "created";
  } else {
    settingsAction = "skipped";
  }

  let mediaSeeded = 0;
  let mediaSkipped = 0;

  for (const media of DEMO_MEDIA) {
    const { pageSlug, ...mediaFields } = media;

    const existing = await db
      .select({ id: websiteMedia.id })
      .from(websiteMedia)
      .where(eq(websiteMedia.originalName, mediaFields.originalName))
      .limit(1);

    if (existing.length > 0) {
      mediaSkipped++;
      continue;
    }

    let pageId: string | null = null;
    if (pageSlug) {
      const pageRow = await db
        .select({ id: websitePages.id })
        .from(websitePages)
        .where(eq(websitePages.slug, pageSlug))
        .limit(1);
      pageId = pageRow[0]?.id ?? null;
    }

    await db.insert(websiteMedia).values({ ...mediaFields, pageId });
    mediaSeeded++;
  }

  console.log(
    `[seed] website_pages: ${pagesUpserted} upserted (status=published, access=public garantidos)`
  );
  console.log(`[seed] website_settings: ${settingsAction} (singleton)`);
  console.log(
    `[seed] website_media: ${mediaSeeded} criadas, ${mediaSkipped} já existiam (idempotente por originalName)`
  );
}
